#!/bin/bash -e


if [[ -d ./fastq ]]; then
   rm -r ./fastq
fi
mkdir ./fastq


srrList=(SRR22214907 SRR22214908 SRR22214909 SRR22214910)
for srr in "${srrList[@]}"; do
    echo Downloading $srr...
    fasterq-dump -p $srr -O ./fastq
    mv fastq/${srr}_1.fastq fastq/${srr}_R1.fastq
    mv fastq/${srr}_2.fastq fastq/${srr}_R2.fastq
    gzip ./fastq/${srr}*.fastq &
done
echo Waiting for the compression of the downloaded fastq files...
wait


# Choose a profile suitable for your system configuration in the below line.
# You might also need to edit nextflow.config file, if none of the pre-defined
# settings reflect your CPU core count and/or RAM available.
# predefined profiles: aws, standard (HPC cluster with slurm) or local_only (e.g. PC without nodes)
../startWorkflow.nf --platform i --in ./fastq --out ./ -profile standard

echo "All done, hopefully well done."
echo Please compare the contents of the analysisResults folder that was generated on your system \
        with the expectedResults folder that was generated by CFSAN.
