#!/bin/bash

mkdir ./fastq

srrList=(SRR18910147 SRR18910148 SRR18910149 SRR18910150)

for srr in "${srrList[@]}"; do			
	echo Downloading $srr...
	fasterq-dump -p $srr -O ./fastq
	# mv fastq/${srr}_1.fastq fastq/${srr}_R1.fastq
	# mv fastq/${srr}_2.fastq fastq/${srr}_R2.fastq
done

echo Compressing downloaded input files...
gzip -v ./fastq/*.fastq


../startWorkflow.nf --platform n --in ./fastq --out ./ 


echo "All done, hopefully well done."
echo Please compare the contents of the analysisResults folder that was generated on your system \
		with the expectedResults folder that was generated by CFSAN.